import { createContext } from "react";



// define upper and lower bounds for all numerical preferences
export const preferenceInputMapper = {
    vaultLockTimeOut: {
        label:"Vault time out (minutes)",
        step: 1,
        min: 1,
        max: 30
    },
    keyRotationPeriod: {
        label: "Key rotation Period (days)",
        step: 5,
        min: 15,
        max: 90
    },
    entriesPerPage: {
        label: "Entries per page",
        step: 1,
        min: 10,
        max: 200
    },
    maxGeneratedPassLength: {
        label: "Maximum length of password generated by randomise password function",
        step : 1,
        min: 1,
        max: 128
    },
    clearClipboardTime : {
        label : "Clear clipboard  (seconds)",
        step: 1,
        min: 5,
        max: 15
    },
}

export const preferenceDefaults = {
    vaultLockTimeOut: 30, // seconds
    keyRotationPeriod: 90, //days
    requireStrongMasterPassword: true,
    entriesPerPage: 50, 
    maxGeneratedPassLength: 50, //characters
    clearClipboardTime: 10, //seconds
    fontSize: 14, //px
    fontSpacing: 1, 
    openLastOpenedVault: true,
    bannerTimeOut: 3000 //milliseconds
}
export type PreferenceType = typeof preferenceDefaults;

export const securityPreferenceDefaults = {
    argonTimeCost: 3,
    argonMemCost: 65536,
    argonParallelism: 4,
}

export type SecurityPreferenceType = typeof securityPreferenceDefaults;

export const securityPreferencePresets:Record<string, SecurityPreferenceType> ={
    'Standard':{
        argonTimeCost: 3,
        argonMemCost: 65536,
        argonParallelism: 4,
    },
    "High":{
        argonTimeCost: 8,
        argonMemCost: 262144,
        argonParallelism: 8,
    },
    "Paranoid":{
        argonTimeCost: 16,
        argonMemCost: 524288,
        argonParallelism: 8,
    }
}


type PreferenceCTXType = {
    preference: PreferenceType,
    setPreference: React.Dispatch<React.SetStateAction<PreferenceType>>
}


export const PreferenceContext = createContext<PreferenceCTXType>({
    preference: {...preferenceDefaults},
    setPreference:(_:PreferenceType)=>{throw new Error('Set prefence called outside of provider')} 
})