import { createContext } from "react";



export type PreferenceType = {
    vaultLockTimeOut: number; //  minutes
    keyRotationPeriod: number; // days
    requireStrongMasterPassword: boolean;
    entriesPerPage: number;
    maxGeneratedPassLength: number; //characters
    clearClipboardTime: number; //seconds
    fontSize: number;
    fontSpacing: number;
    openLastOpenedVault: boolean; // like how VS code opens the files that you were working on previously rahter than finding them again
}

// define upper and lower bounds for all numerical preferences
export const preferenceInputMapper = {
    vaultLockTimeOut: {
        label:"Vault time out (minutes)",
        step: 1,
        min: 1,
        max: 30
    },
    keyRotationPeriod: {
        label: "Key rotation Period (days)",
        step: 5,
        min: 15,
        max: 90
    },
    entriesPerPage: {
        label: "Entries per page",
        step: 1,
        min: 10,
        max: 200
    },
    maxGeneratedPassLength: {
        label: "Maximum length of password generated by randomise password function",
        step : 1,
        min: 1,
        max: 128
    },
    clearClipboardTime : {
        label : "Clear clipboard  (seconds)",
        step: 1,
        min: 5,
        max: 15
    },
}

export const preferenceDefaults: PreferenceType = {
    vaultLockTimeOut: 30,
    keyRotationPeriod: 90,
    requireStrongMasterPassword: true,
    entriesPerPage: 50,
    maxGeneratedPassLength: 50,
    clearClipboardTime: 10,
    fontSize: 14,
    fontSpacing: 1,
    openLastOpenedVault: true
}


type PreferenceCTXType = {
    preference: PreferenceType,
    setPreference: React.Dispatch<React.SetStateAction<PreferenceType>>
}


export const PreferenceContext = createContext<PreferenceCTXType>({
    preference: {...preferenceDefaults},
    setPreference:(_:PreferenceType)=>{throw new Error('Set prefence called outside of provider')} 
})